CREATE TABLE CUSTOMERS (
	CUSTOMER_ID SERIAL NOT NULL PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(255),
	CONTACT_NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	CITY VARCHAR(255),
	POSTAL_CODE VARCHAR(255),
	COUNTRY VARCHAR(255)
);